SELECT 
    t.PICKUP_HOUR, 
    t.RIDES AS actual_rides, 
    p.PREDICTED_RIDES AS predicted_rides
FROM NYC_DATA.PUBLIC.YELLOW_TAXI_DATA_TRANSFORMED t
LEFT JOIN NYC_DATA.PUBLIC.YELLOW_TAXI_DATA_PREDICTIONS p
    ON t.PICKUP_HOUR = p.PICKUP_HOUR
    AND t.PICKUP_LOCATION_ID = p.PICKUP_LOCATION_ID
WHERE t.PICKUP_LOCATION_ID = 161
ORDER BY t.PICKUP_HOUR DESC
LIMIT 100;